[package]
name = "epsilon-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ecore = { git = "https://github.com/BloodWalrus/epsilon-core" }
glam = "0.21.2"